### ISSUE TITLE
I have a problem.

### ISSUE THREAD

**Issue by Pengfei00** [bluec0re/python-wcfbin#6]
from wcf.records import Record, print_records
data = requests.post('http://106.37.208.233:20035/ClientBin/Env-CnemcPublish-RiaServices-EnvCnemcPublishDomainService.svc/binary/GetAllCityDayAQIModels').content
records = Record.parse(data)

but error:  
File "D:\untitled\wcf\records\base.py", line 126, in parse
    log.debug('Value: %s' % str(obj))
TypeError: **str** returned non-string (type bytes)

**Comment by bluec0re** [comment]
Seems a python 3 issue to me. Did you used python 3 or 2? And if 3, could you test it with python2? To narrow down the issue.

Thanks!

**Comment by Pengfei00** [comment]
i use python3 have error

python2 run well

thanks
